version: '3'


services:
  pelis-api:
    image: pelis-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    container_name: pelis-api
    depends_on:
      - db

  db:
    image: postgres:14.3
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: pelis-db
    volumes:
      - ./postgres:/var/lib/postgresql/data